---
stages:
  - build-development
  - test
  - pre-deploy
  - build-production
  - publish

include:
  - project: 'platform/gitlab-jobs'
    file: 'jobs.web.yml'

job-test:
  extends: .job-npm-ci-test-cover

job-release-minor:
  extends: .job-release-it-minor

job-release-major:
  extends: .job-release-it-major

job-publish:
  extends: .publish
  before_script:
    - npm ci --include=dev
